### ISSUE TITLE
Add `null | undefined` to `Primitive` and `isPrimitive`

### ISSUE THREAD

**Issue by dosentmatter** [piotrwitek/utility-types#113]
## Is your feature request related to a real problem or use-case?

See:
https://www.typescriptlang.org/docs/handbook/basic-types.html#object
> `object` is a type that represents the non-primitive type, i.e. anything that is not `number`, `string`, `boolean`, `symbol`, `null`, or `undefined`.

Currently, we have `export type Primitive = number | bigint | boolean | string | symbol;`. We are missing `null` and `undefined`.

The [complete list](https://mariusschulz.com/blog/the-object-type-in-typescript) is
>`string | boolean | number | bigint | symbol | null | undefined`

## Describe a solution including usage in code example

```ts
export type Primitive = number | bigint | boolean | string | symbol | null | undefined;
```

```ts
export const isPrimitive = (val: unknown): val is Primitive => {
  if (val === null || val === undefined) {
    return true;
  }
  switch (typeof val) {
    case 'string':
    case 'symbol':
    case 'number':
    case 'bigint':
    case 'boolean': {
      return true;
    }
    default:
      return false;
  }
};
```

## Who does this impact? Who is this for?

TypeScript users

**Comment by piotrwitek** [comment]
Hey @dosentmatter 
This is a valid point and I agree with that.
Contributions welcome!
