### ISSUE TITLE
keyof PickByValue<ObjectWithOptionals, SomeType> gives union with `undefined`

### ISSUE THREAD

**Issue by vatosarmat** [piotrwitek/utility-types#123]
## Description

`PickByValue`, `PickByValueExact` and maybe other operators `Pick`ing keys union created via "conditional mapping" produce types with "hidden" `undefined` key when used on type with optional properties. Applying `keyof` to such types gives `ACTUAL_KEYS | undefined`.

Details and suggested fix here:
https://github.com/microsoft/TypeScript/issues/34992

## Steps to Reproduce
[Playground](http://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=20&pc=2#)

**Comment by piotrwitek** [comment]
Suggested fix looks good, let's make it happen! Accepting PRs.
