### ISSUE TITLE
[feat]: SetDifference between no-string types

### ISSUE THREAD

**Issue by AbraaoAlves** [piotrwitek/utility-types#14]
Is it possible?

``` typescript
import { SetDifference } from 'utility-types';

type c = SetDifference<object | string | number, object | number>;
// Expect: number
```

**Comment by piotrwitek** [comment]
Currently no, but with conditional types on the typescript@next branch, that might be possible.

Btw. what is your use case for that requirement, doesn't a typeof type guard do the job?

**Comment by piotrwitek** [comment]
@AbraaoAlves I actually checked and it should indeed be possible to implement
I'll soon start to experiment on the next branch
