### ISSUE TITLE
$ReadOnly<T> has a typo in its documentation

### ISSUE THREAD

**Issue by cyli2014** [piotrwitek/utility-types#156]
## Description

The documentation for `$ReadOnly<T>` seems to have a typo.
```js
import { $ReadOnly } from 'utility-types';

type Props = { name: string; age: number; visible: boolean };

// Expect: Readonly<{ name: string; age?: number | undefined; visible: boolean; }>
type ReadOnlyProps = $ReadOnly<Props>;
```

The example shows that `age` is converted to an optional property after being applied `$ReadOnly`. I thinks it's a typo because `age` should be an ordinary readonly property just like `name` and `visible`.

## Steps to Reproduce

1. Refer to [$ReadOnly<T>](https://github.com/piotrwitek/utility-types#readonly2) in [README.md](https://github.com/piotrwitek/utility-types/blob/master/README.md)

## Expected Behavior

```js
import { $ReadOnly } from 'utility-types';

type Props = { name: string; age: number; visible: boolean };

// Expect: Readonly<{ name: string; age: number; visible: boolean; }>
type ReadOnlyProps = $ReadOnly<Props>;
```

## Suggested Solution(s)

Modify the documentation in [README.md](https://github.com/piotrwitek/utility-types/blob/master/README.md) and comments in [utility-types.ts](https://github.com/piotrwitek/utility-types/blob/master/src/utility-types.ts)

## Project Dependencies
- Utility-Types Version: 3.10.0

## Environment (optional)

- Browser and Version: XXX
- OS: XXX
- Node Version: XXX
- Package Manager and Version: XXX

**Comment by cyli2014** [comment]
BTW, some npm scripts don't work well on Windows. Any plan for compatibility?

**Comment by piotrwitek** [comment]
You're right, thanks for the fix!

I'm not using windows so I cannot help, but if you can add Windows compatibility it would be great!

**Comment by cyli2014** [comment]
Gotcha. Will look into it if time permits. Thanks!
