### ISSUE TITLE
what does this `-?` spec? and where I can get such related grammar

### ISSUE THREAD

**Issue by xkx9431** [piotrwitek/utility-types#159]
First of all please check our spectrum community chat and we recommend to ask your question there for a quickest response and the indexing in search engines: 
- https://spectrum.chat/utility-types

The only good reason to use issue tracker for your questions would be for "special requests" that doesn't fit into bug reports and feature requests categories.
hi , I just read your code , and I want know, what the dash  **-** means inside   `[K in keyof T]-?`  ?

```ts
export type FunctionKeys<T extends object> = {
  [K in keyof T]-?: NonUndefined<T[K]> extends Function ? K : never;
}[keyof T];
```.

just give some suggestions and close this issue will be ok. thanks

**Comment by piotrwitek** [comment]
It means to remove optional modifier on object keys.

Please check the mapped types in TS Docs.
