### ISSUE TITLE
Idea is Great, Why don't you commit your types utility to Typescript official built-in rather extra types?

### ISSUE THREAD

**Issue by ericchanyoov** [piotrwitek/utility-types#178]
First of all please check our spectrum community chat and we recommend to ask your question there for a quickest response and the indexing in search engines: 
- https://spectrum.chat/utility-types

The only good reason to use issue tracker for your questions would be for "special requests" that doesn't fit into bug reports and feature requests categories.

**Comment by piotrwitek** [comment]
Hey, I never tried but I think that's the userland domain and would never be accepted to the core library. You can try if you wish, it's open source and anyone can pick-up the code from here and submit it to TS as proposal.
