### ISSUE TITLE
Is there any way to use these types without import 'utility-types'

### ISSUE THREAD

**Issue by FrankFang** [piotrwitek/utility-types#188]
For now:

```typescript
import { Optional } from 'utility-types'
type X = Optional<Person, 'name'>
```

What I expected is:

```typescript
type X = Optional<Person, 'name'>
```

I've tried [Triple-Slash Directives](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html), but it did not work.

**Comment by piotrwitek** [comment]
`import type { Optional } from 'utility-types'`

**Comment by FrankFang** [comment]
I mean using type Optional without any import statement.
Is that possible?

**Comment by piotrwitek** [comment]
should be, if you declare it in the global space. But kee pin mind it was not designed to be used like that so you need to figure it out on your own. Sorry
