### ISSUE TITLE
React utility types ( eg React.ElementProps )

### ISSUE THREAD

**Issue by dmisdm** [piotrwitek/utility-types#20]
So since conditional types have been introduced, i found out how to do this.
Been wanting this for ages.

Flow (i think its right)...you get the point
```
const TestComponent = ({one}: {one: number}) => <div>{one}</div>

type TestProps = React.ElementProps<typeof TestComponent>
// TestProps = {one: number}
```

Typescript:
```
type ElementProps<T> = T extends React.ComponentType<infer Props>
  ? Props extends object ? Props : never
  : never;

const TestComponent = ({one}: {one: number}) => <div>{one}</div>;

type TestProps = ElementProps<typeof TestComponent>;
// TestProps = {one: number}
```
`ElementProps` is really just `TypeOfFirstArg` but using react's component types

So maybe also worth adding:
```
type FirstArg<T extends Function> = T extends (arg: infer A) => any ? A : never;
```

Not sure if thats the best way and if iv used the best types in react. Maybe best to not add react stuff to this library?

**Comment by piotrwitek** [comment]
I have it in mind, but didn't wanted to clutter it with React types dependency, will think about it

**Comment by piotrwitek** [comment]
It's no longer needed as it's already included in the react types:

```ts
type TodoItemProps = React.ComponentProps<typeof TodoItem>;
```
