### ISSUE TITLE
$ElementType not infer union of literals

### ISSUE THREAD

**Issue by darky** [piotrwitek/utility-types#25]
What's happen?:

```typescript
$ElementType<['a', 'b', 'c'], number> // any
```

What should be:

```typescript
$ElementType<['a', 'b', 'c'], number> // 'a' | 'b' | 'c'
```

**Comment by eps1lon** [comment]
What Typescript version are you using? I'm having no problems with 2.9.2. Documentation says that you need at least `2.8.1` for utility-types `2.x`

@piotrwitek Might be a good idea to add that typescript version as a `peerDependency`

**Comment by darky** [comment]
2.9.2

**Comment by eps1lon** [comment]
Might be a good idea to provide a repo and where/how the error is displayed. Some editors for example have to be configured to use a specific ts version.

**Comment by darky** [comment]
Sorry, I wrong.

I try like:

```
$ElementType<Pick<{a: ['a', 'b', 'c']}, 'a'>, number>
```

But works:

```
$ElementType<$PropertyType<{a: ['a', 'b', 'c']}, 'a'>, number>
```
