### ISSUE TITLE
DeepRequired Type

### ISSUE THREAD

**Issue by jkillian** [piotrwitek/utility-types#32]
The TypeScript standard library includes a [`Required` type](https://github.com/Microsoft/TypeScript/blob/f53a27eac0ee702bd14d984deaecadfb42181c99/src/lib/es5.d.ts#L1401), but this only operates on the top-most level of fields in a type. A `DeepRequired` type, [perhaps something like this](https://github.com/Microsoft/TypeScript/issues/15012#issuecomment-365453623), would be useful.

```ts
interface Example {
  foo?: { bar?: number }
}

// Required<Example>
{
  foo: { bar?: number }
}

// DeepRequired<Example>
{
  foo: { bar: number }
}
```

**Comment by malash** [comment]
I believe this PR fixed it. https://github.com/piotrwitek/utility-types/pull/33
