### ISSUE TITLE
What is meant by "Provides multiple output formats"?

### ISSUE THREAD

**Issue by carpben** [piotrwitek/utility-types#39]
I want to start using this library, but was surprised to read that it "Provides multiple output formats (es5-commonjs, es5-module, jsnext)". Isn't this library simply Typescript? I'd like to leave the compilation to Typescript and/or Babel.

**Comment by piotrwitek** [comment]
Hey, yes you're right it is!
This is some stuff I copied from my other library readme and haven't noticed. I need to remove it.
