### ISSUE TITLE
support $Compose

### ISSUE THREAD

**Issue by stereobooster** [piotrwitek/utility-types#45]
There is no documentation for it except this https://github.com/facebook/flow/blob/v0.87.0/src/typing/type_annotation.ml#L593

This is how people doing it https://github.com/reduxjs/redux/blob/686d29b5d4e2dcb6709c16e31b79ecde90763156/index.d.ts#L451-L541

**Comment by piotrwitek** [comment]
I'm not sure about this one as it isn't in the official public API

**Comment by piotrwitek** [comment]
Thanks for all references, but for me it looks like a solution for a single use-case which is to provide type definition for a composition function.
I don't think it fits this library which is a collection of general types.

**Comment by stereobooster** [comment]
makes sense
