### ISSUE TITLE
Flow's Class<T>

### ISSUE THREAD

**Issue by levenleven** [piotrwitek/utility-types#47]
[Class\<T>](https://flow.org/en/docs/types/utilities/#toc-class)
> Given a type T representing instances of a class C, the type Class<T> is the type of the class C

Similar can be achieved in Typescript by `typeof Foo` but requires `Foo` to be a value, not a type. So can't be used with generics

Constructor part can be easily described by: `type Constructor<T> = new (...args) => T;`. This of course won't include any static members and won't verify inheritance (classes in Typescript not treated as nominal)

Maybe it is good enough to include only "constructor part"?

**Comment by piotrwitek** [comment]
I think what you proposed is good enough.
```ts
type Class<T> = new (...args) => T
```
It works correctly for all Flow use case examples (except nominal part but we don't care about it as TS is structural)

I accept PR

**Comment by levenleven** [comment]
Great, I'll create a PR
