### ISSUE TITLE
Add DeepPartial<T>

### ISSUE THREAD

**Issue by piotrwitek** [piotrwitek/utility-types#52]
The same as `Partial` but working recursively

**Comment by levenleven** [comment]
Something like
```typescript
export type DeepPartial<T> =
	T extends Array<infer U> ? PartialArray<U> :
	T extends object ? PartialObject<T> :
	T | undefined;

interface PartialArray<T> extends Array<DeepPartial<T>> { }
type PartialObject<T> = {
	[P in keyof T]?: DeepPartial<T[P]>;
};
```
?

**Comment by piotrwitek** [comment]
Yeah, although there are two possible improvements we can make here:
- T extends (...args: any[]) => any ? T : ... - so that extracted function properties types works correctly
here is type snapshot for that:
```
type NestedFunctionProps = {
    first?: {
      second?: (value: number) => string;
    };
  };
  // @dts-jest:pass:snap -> _DeepRequiredObject<{ second?: ((value: number) => string) | undefined; }>
  testType<DeepRequired<NestedFunctionProps>['first']>();
  // @dts-jest:pass:snap -> (value: number) => string
  testType<DeepRequired<NestedFunctionProps>['first']['second']>();
  // @dts-jest:pass:snap -> string
  testType<ReturnType<DeepRequired<NestedFunctionProps>['first']['second']>>();
```
- inline PartialArray interface using conditional with infer clause in DeepPartial definition

**Comment by levenleven** [comment]
Nice catch with function properties!
Regarding _inline PartialArray_ - if you mean `T extends Array<infer U> ? Array<DeepPartial<U>>` this can't be done because type alias can't be referenced by itself at the top level

**Comment by piotrwitek** [comment]
Ok please let me double check the inline case, I thought I saw it working somewhere with a little trick
