### ISSUE TITLE
Support RequiredKeys and OptionalKeys

### ISSUE THREAD

**Issue by malash** [piotrwitek/utility-types#53]
Demo:

```ts
type Obj = {
  a: number;
  d: number | undefined
  b?: string;
  c?: boolean;
  e?: number | undefined
};
type A = RequiredKeys<Obj>; // "a" | "d"
type B = OptionalKeys<Obj>; // "b" | "c" | "e"
```

https://stackoverflow.com/questions/53809467/typescript-how-get-optional-keys-of-type

EDIT1: Added edge cases

**Comment by levenleven** [comment]
I'd like to add `NullableKeys` as well.
With _strictNullChecks_ enabled can be implemented as
```typescript
type PickKeys<T extends object, TValue extends null | undefined> = NonNullable<
  { [K in keyof T]: TValue extends T[K] ? K : never }[keyof T]
>

type NullableKeys<T extends object> = PickKeys<T, null>
type OptionalKeys<T extends object> = PickKeys<T, undefined>
type RequiredKeys<T extends object> = Exclude<keyof T, OptionalKeys<T>>
```

[Playground](https://www.typescriptlang.org/play/index.html#src=type%20PickKeys%3CT%20extends%20object%2C%20TValue%20extends%20null%20%7C%20undefined%3E%20%3D%20NonNullable%3C%0A%09%7B%20%5BK%20in%20keyof%20T%5D%3A%20TValue%20extends%20T%5BK%5D%20%3F%20K%20%3A%20never%20%7D%5Bkeyof%20T%5D%0A%3E%0A%0Atype%20NullableKeys%3CT%20extends%20object%3E%20%3D%20PickKeys%3CT%2C%20null%3E%0Atype%20OptionalKeys%3CT%20extends%20object%3E%20%3D%20PickKeys%3CT%2C%20undefined%3E%0Atype%20RequiredKeys%3CT%20extends%20object%3E%20%3D%20Exclude%3Ckeyof%20T%2C%20OptionalKeys%3CT%3E%3E%0A%0Atype%20Foo%20%3D%20%7B%0A%09str%3A%20string%0A%09num%3A%20number%0A%09date%3A%20Date%20%7C%20null%0A%09bool%3F%3A%20boolean%0A%7D%0A%0Atype%20N%20%3D%20NullableKeys%3CFoo%3E%20%2F%2F%20%22date%22%0Atype%20O%20%3D%20OptionalKeys%3CFoo%3E%20%2F%2F%20%22bool%22%0Atype%20R%20%3D%20RequiredKeys%3CFoo%3E%20%2F%2F%20%22str%22%20%7C%20%22num%22%20%7C%20%22date%22) (works only with **strictNullChecks**)

**Comment by piotrwitek** [comment]
@levenleven 
Although they might seem useful API surface will expand making it complex and hard to learn.
Now I think that maybe it would be better to add more generic types to allow consumer for better composability making it easier to master and allowing for even better flexibility and extendability:
```
type ExtractKeys<T extends object, TKeyValue extends any> = NonNullable<
  { [K in keyof T]: TKeyValue extends T[K] ? K : never }[keyof T]
>;
type ExcludeKeys<T extends object, TKeyValue extends any> = Exclude<keyof T, ExtractKeys<T, TKeyValue>>;

type Foo = {
  str: string;
  num: number;
  date: Date | null;
  bool?: boolean;
};

type NullableProps = Pick<Foo, ExtractKeys<Foo, null>>;
type OptionalProps = Pick<Foo, ExtractKeys<Foo, undefined>>;
type RequiredProps = Pick<Foo, ExcludeKeys<Foo, undefined>>;
```

What do you think?

**Comment by levenleven** [comment]
I think `ExtractKeys`/`ExcludeKeys` are good for flexibility, but I'd also include shortcuts to `RequiredKeys` and others.

Now regarding names: 
1. Key helpers - maybe it would be clearer if we'd call them `ExtractKeysOfType` or `KeysAssignableTo`?
2. Property set helpers (not sure if needed or in scope of this proposal) - `PickNullable`, `PickOptional` etc.

**Comment by piotrwitek** [comment]
I agree we could greatly benefit from both general helpers and shortcuts.

## New API Proposal for extending Pick/Omit and Object-Keys Helpers

### General: (we need to have consistent convention between `Keys` and `Pick` helpers and have variations for matching by assignability and exact type)
- KeysIncludingType<TObj, TValue> (will grab unions)
- KeysExcludingType<TObj, TValue> (will grab unions)
- KeysMatchingType<TObj, TValue> (only exact type)
- PickByType<TObj, TValue>
- PickByExactType<TObj, TValue>
- OmitByType<TObj, TValue>
- OmitByExactType<TObj, TValue>

### Shortcuts:
Existing:
- FunctionKeys<TObj>
- NonFunctionKeys<TObj>
New:
- RequiredKeys<TObj>
- OptionalKeys<TObj> or PartialKeys<TObj> (inconsistency - we need to normalize it with Partial/Optional type)
- ReadonlyKeys<TObj> - from #55 
- WritableKeys<TObj> - from #55
- NullableKeys<TObj>
- NonNullableKeys<TObj>

Open for feedback/improvements!

**Comment by piotrwitek** [comment]
I understand your semantics argument, but in reality Partial equals Optional. In general I think Optional would be a better name and for that reason I think the best would be to use OptionalKeys and create an alias (Optional) for Partial as well to keep the API consistent.

**Comment by malash** [comment]
I find a bug in the StackOverflow version.

```ts
type KeysOfType<T, U> = { [K in keyof T]: T[K] extends U ? K : never }[keyof T];
type RequiredKeys<T> = Exclude<KeysOfType<T, Exclude<T[keyof T], undefined>>, undefined>;
type OptionalKeys<T> = Exclude<keyof T, RequiredKeys<T>>;

type Obj = {
  a: any;
  b?: string;
  c?: boolean;
};
type A = RequiredKeys<Obj>; // "a" | "b" | "c"
type B = OptionalKeys<Obj>; // never
```

**Comment by malash** [comment]
And another issue is that how to handle `{ d: number | undefined }` ?

Should its `RequiredKeys` be `'d'` or `never` ?

**Comment by malash** [comment]
@piotrwitek I think it could be better if we create a new issue for the new API proposal ?

**Comment by levenleven** [comment]
@malash see above working version.

Regarding `number | undefined` - I think this should be treated as optional, because what `?` essentially does - is adding undefined to the type (with strictNullChecks of course)

**Comment by malash** [comment]
```ts
type A = Required<{ a: number | undefined }>;
type B = Required<{ a?: number }>;
```

`A` is still `{ a: number | undefined }`

**Comment by levenleven** [comment]
@malash interesting, seems you're right. We'll need to tweak Required/Optional resolution

**Comment by eps1lon** [comment]
Depending on the implementation (`Object.prototype.hasOwnProperty` can make a difference here) those are not the same thing. The first one still requires explicitly setting `a` to `undefined` while you can do this implicitly with the second one by omitting `a`. You could argue that `Required` is working as intended.

**Comment by eps1lon** [comment]
Right because I would argue that `RequiredKeys` should include `number | undefined`. After all the **key** is required. Just not the **value**.
