### ISSUE TITLE
Support ReadonlyKeys and WritableKeys

### ISSUE THREAD

**Issue by levenleven** [piotrwitek/utility-types#55]
Demo:
```typescript
type Obj = {
  readonly a: number;
  b: string;
};
type A = ReadonlyKeys<Obj>; // "a"
type B = WritableKeys<Obj>; // "b"
```

Can be based on https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir

**Comment by piotrwitek** [comment]
Yeah both of them are quite useful. Accepting PR's!
