### ISSUE TITLE
TestCase for the types

### ISSUE THREAD

**Issue by Kingwl** [piotrwitek/utility-types#64]
Hi, Thanks for your working.
I noticed that there was no test in the repo.
And i wrote a tools maybe helpful for the type test:  https://github.com/HearTao/ts-baseline
That was extracted from the typescript test runner

**Comment by piotrwitek** [comment]
Hey, not sure what you mean but code-base is 100% covered with type-tests.
Also please note this is not a good place for advertisements so do not spam issue board.
