### ISSUE TITLE
Proposal Brand type

### ISSUE THREAD

**Issue by airtoxin** [piotrwitek/utility-types#66]
branded type is known as nominal type in other language.

Demo

```typescript
type Brand<K, T> = K & { __brand: T }

type USD = Brand<number, "USD">
type EUR = Brand<number, "EUR">

const usd = 10 as USD;
const eur = 10 as EUR;

function gross(net: USD, tax: USD): USD {
  return (net + tax) as USD;
}

gross(usd, usd); // ok
gross(eur, usd); // Type '"EUR"' is not assignable to type '"USD"'.
```

Reference: https://michalzalecki.com/nominal-typing-in-typescript/

Naming of `_brand` property  and `Brand` type is convention in typescript team.
https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=brand&type=

**Comment by piotrwitek** [comment]
Ok, looks good. Accepting PRs.
