### ISSUE TITLE
New Suggestions

### ISSUE THREAD

**Issue by ersimont** [piotrwitek/utility-types#69]
I don't know how or if you'd like suggestions like this, but I just found this library, I'd like to use it, and it would be cool to get some more of the utility types I use from here. Happy to move any of these that sound interesting to a separate issue, or to just close this if none of them do.

```ts
export interface ClassFor<T> {
  new (...args: unknown[]): T;
}

export interface ObjectWith<T> {
  [key: string]: T;
}

/** @hidden */
export interface NumberKeyedObject<T = unknown> {
  [key: number]: T;
}

export type Primitive = number | boolean | string;
export type Existant = Primitive | object;
export type Nil = null | undefined;
export type Falsey = Nil | false | 0 | ""; // | NaN

export type Function0<R> = () => R;
export type Function1<T1, R> = (t1: T1) => R;
export type Function2<T1, T2, R> = (t1: T1, t2: T2) => R;
export type Function3<T1, T2, T3, R> = (t1: T1, t2: T2, t3: T3) => R;
export type Function4<T1, T2, T3, T4, R> = (
  t1: T1,
  t2: T2,
  t3: T3,
  t4: T4,
) => R;

export type Transformer<T> = (input: T) => T;
```

**Comment by piotrwitek** [comment]
Hey @ersimont, thanks for the suggestion, let me go through them one by one:

- ClassFor - not really useful for a generic library like this, should be declared locally
- ObjectWith<T> === Record<string, T> - redundant
- Primitive - OK, this might be a common use-case
- Existant - it's a rather rare case I would just use it inline
- Nil === void - redundant
- Falsey - I don't understand how that might be useful? any use-case example?
- FunctionX - not useful for this library, use locally for your use-case
- Transformer - not really useful for this library, I could annotate a function and get the same result in fewer characters

Primitive is ok to add. Note it's missing symbol primitive

**Comment by ersimont** [comment]
Thank you for taking the time to look at these. Thanks for pointing out the ones that already exist by another name! Let me know if you want a separate issue filed for `Primitive` or anything like that.

You asked about `Falsey`. I used it for [my implementation of compact](https://github.com/simontonsoftware/micro-dash/blob/master/projects/micro-dash/src/lib/array/compact.ts#L11):
```ts
function compact<T>(array: Array<T | Falsey>): T[];
```

**Comment by piotrwitek** [comment]
@ersimont Ok now I see it better, I would add:
```ts
export type Primitive = number | boolean | string | symbol;
export type Falsey = null | undefined | false | 0 | "";
```
You can put them in the top of mapped-types file and please include @example jsdocs. Then add a new section in TOC called "Aliases" (it should be a new first section now). 

Please open single new PR for adding both.

BTW: I also improved your `compact` function declaration to retain correct type-soundness:
```ts
export function compact<T>(array: Array<T | Falsey>) {
  return array.filter(a => a) as Exclude<T, Falsey>[];
}

// Expect: const r: ("a" | "b")[]
const r = compact(['a', 'b', null, undefined, false, 0, '']);
```

**Comment by ersimont** [comment]
PR filed. Thanks for the suggestion about `compact`. That let me remove the first `| Falsey` too:

```ts
export function compact<T>(array: Array<T>) {
  return array.filter(identity) as Array<Exclude<T, Falsey>>;
}
```

**Comment by piotrwitek** [comment]
It was merged, closing
