### ISSUE TITLE
_DeepReadonlyArray does not count as array

### ISSUE THREAD

**Issue by thomasvanlankveld** [piotrwitek/utility-types#76]
For the following code:

```typescript
import { DeepReadonly } from 'utility-types';

type Thing = { prop: string };
type Arr = DeepReadonly<Thing[]>;

function first<T>(arr: T[]) {
  return arr[0];
}

const arr: Arr = [{ prop: 'foo' }];
const initial = first(arr);
```

I get:

```
Argument of type '_DeepReadonlyArray<Thing>' is not assignable to parameter of type '_DeepReadonlyObject<Thing>[]'.
  Type '_DeepReadonlyArray<Thing>' is missing the following properties from type '_DeepReadonlyObject<Thing>[]': pop, push, reverse, shift, and 3 more.ts(2345)
```

**Comment by piotrwitek** [comment]
Hey, thanks for the report I know how to fix it

**Comment by piotrwitek** [comment]
Ok I double checked, and the error is ok because your code is not safe at runtime.

If your structure is Readonly it cannot have methods like pop because it's mutable method.

here is a correct constrain
```ts
type Thing = { prop: string };
type Arr = DeepReadonly<Thing[]>;

function first<T extends ReadonlyArray<any>>(arr: T) {
  return arr[0];
}

const arr: Arr = [{ prop: 'foo' }];
const initial = first(arr);
```

**Comment by thomasvanlankveld** [comment]
Good call, the suggestion solves my problem, thanks!

**Comment by ammaraltahan** [comment]
Hi
I am also getting this, as my root state contains DeepReadonly arrays for different object sets, and I'm running into this as well, I tried to implement the same fix, but I'm getting:

`Module '"../../../node_modules/utility-types/dist"' has no exported member 'ReadonlyArray'.ts(2305)`
