### ISSUE TITLE
[New type request] Flatten<T>

### ISSUE THREAD

**Issue by Favna** [piotrwitek/utility-types#85]
## Is your feature request related to a real problem or use-case?

In the fuzzy searching library [Fuse.JS](https://github.com/krisk/Fuse) it is supported to search for deep nested keys by giving them as `['leve1.level2.level3']` etc. However making a typing of this system is very hard (to be frank, I haven't even figured it out at all yet) given a single type `T`. Being able to supply `Flatten<T>` where an type such as:

```ts
type TypeWithNestedKeys = {
  foo: {
    bar: {
      baz: string;
      blub: {
        bloo: string
      }
    }
  };
  key: string | string[];
  prop: boolean;
}
```

Would get parsed to:

```ts
type flattened = Flatten<TypeWithNestedKeys>;

// Expect: {
//   'foo.bar.baz': string;
//   'foo.bar.blub.bloo': string;
//   'key': string | string[];
//   'prop': boolean;
// }
```

## Describe a solution including usage in code example

See above for some code examples. Sadly I have not delved into TS that far that I can provide potential solutions.

## Who does this impact? Who is this for?

This is primarily for Fuse.JS users however I think it can aid all TypeScript users who want to take their typings to the next level.

## Describe alternatives you've considered (optional)

A temporary solution for this particular library is to type Keys as:
```ts
keys?: (keyof T)[] | T[keyof T] | { name: keyof T; weight: number }[];
```

Which would result in this typing:

![image](https://user-images.githubusercontent.com/4019718/58347683-c47c0b00-7e5e-11e9-821e-6330d1830f07.png)

However as you can probably tell this is not ideal as it adds a LOT of options for the typings when many are really not necessary.

## Additional context (optional)

I was made aware of the wrong typings on the library through [this issue](https://github.com/krisk/Fuse/issues/261). I aimed to fix them in the past then today a new comment came in about deep nested keys. While as described above I did find the solution, I think a better solution would be possible with this addition to this library.

**Comment by piotrwitek** [comment]
Hey, unfortunately proposed solution is not possible to achieve in Typescript. The solution that is possible is to use array of strings instead of concatenated strings as keys. Let me know if that is something  supported by Fuse.
```ts
keys: [['author', 'first name'], 'taaag']
```

**Comment by Favna** [comment]
Ah that's a real shame. Unfortunately, at least as far as I know that is not an option for Fuse. I suppose maybe in some future release of TS they'll make a feature like this possible but I kind of doubt it sadly.

(Likewise do I doubt it would get enough traction when requesting it there)

**Comment by Favna** [comment]
Doesn't really change anything about being possible in TypeScript or not but I just wanted to update this issue since I've been messing around a bit today and I found some interesting stuff imho. Given these types:
```ts
type Worfklow = {
  inputParameters: Input[];
  outputParameters: Output[];
  steps: Step[];
  displayName: string;
}

type Ticket = {
  ticketId: string;
  title: string;
  assignedTo: string;
  assignmentGroup: string;
  shortDescription: string;
  workflow: Worfklow;
}
```

a union of `("ticketId" | "title" | "assignedTo" | "assignmentGroup" | "shortDescription" | "workflow" | "inputParameters" | "outputParameters" | "steps" | "displayName")[]` can be generated with:

```ts
type sample = (RequiredKeys<Ticket[keyof PickByValue<Ticket, object>]> | OptionalKeys<Ticket[keyof PickByValue<Ticket, object>]> | keyof Ticket)[]
```

or of course with a generic:
```ts
type sample =
(RequiredKeys<T[keyof PickByValue<T, object>]>
    | OptionalKeys<T[keyof PickByValue<T, object>]>
    | keyof T
  )[]
```

Combining this with the "deep" logic (as you can see, the `inputParameters` is itself an array of another type for example) this lib already has for some of the utility types I theorise (maybe a bit too eagerly) that given TypeScript gets the option to do something like:
```ts
type SumOf<T,K> = T + K;

// Expected: "aa.bb"
type sample = SumOf<"aa.", "bb">;
```
the desired effect of what I wrote initially could be achieved.

But I'll just restate that's just my theory and I may be a bit too eager here.

**Comment by piotrwitek** [comment]
Closing as the initially requested type is impossible to do currently in typescript. 
Regarding the second request `SumOf` type, feel free to create a new issue to investigate.

**Comment by namnm** [comment]
@piotrwitek Is this possible yet with "Template Literal Types":
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#template-literal-types

```ts
type Color = "red" | "blue";
type Quantity = "one" | "two";
 
type SeussFish = `${Quantity | Color} fish`;
// type SeussFish = "one fish" | "two fish" | "red fish" | "blue fish"
```
