### ISSUE TITLE
BigInt Support

### ISSUE THREAD

**Issue by 9SMTM6** [piotrwitek/utility-types#86]
## Is your feature request related to a real problem or use-case?
Adding BigInt to the Primitive type as [its slated to become one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt).

## Describe a solution including usage in code example
```ts
type Primitive = number | boolean | string | symbol | bigint
```

## Who does this impact? Who is this for?
Users using the Stage 3 Proposal of Bigint and [Typescript >=3.2](https://devblogs.microsoft.com/typescript/announcing-typescript-3-2/)

## Describe alternatives you've considered (optional)
As I'm not sure how good support for the (JS, not the TS kind of 'overload') typeof operator of eventually employed polyfills is, and how older TS implementations behave with this unknown type, we might want to hold back on that for now, or guard this implementation.

## Additional context (optional)
[Partially Linked in the text before]
* [Microsofts devblog to TS 3.2 which added BigInt support](https://devblogs.microsoft.com/typescript/announcing-typescript-3-2/)
* [MDN entry for BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt)
* MDN entry for typeof](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof)

**Comment by piotrwitek** [comment]
Hey @9SMTM6, thanks for the proposal, I think it's a valid suggestion and JS shouldn't be a concern of this library as we're not using it and consumer is responsible for its own polyfills.

Accepting PR.
