### ISSUE TITLE
Add type guards for some simple types

### ISSUE THREAD

**Issue by 9SMTM6** [piotrwitek/utility-types#88]
## Is your feature request related to a real problem or use-case?
Yes. Type guards are a nice solution for type-flow in typescript.

## Describe a solution including usage in code example
```ts
const isPrimitive = (val: unknown): val is Primitive => {
    switch (typeof val) {
        case 'string':
        case 'symbol':
        case 'number':
        case 'bigint':
        case 'boolean': {
            return true;
        }
        default: return false;
    }
};

const isFalsey = (val: unknown): val is Falsey => !val;

const valConsumer =  (testVal: unknown) => {
    if (!isPrimitive(testVal)) {
         // do stuff
        return 'isComplex';
    }
    type TestVal = typeof testVal; // == Primitive
    // do stuff
    return 'isPrimitive';
};
```

## Who does this impact? Who is this for?
All the users that have to support a more universal API and want to test for specific usecases with immediate TS support without explicit casting or having to write their own type guards.

## Additional context (optional)
* [Official Documentation for Type Guards in TS](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types)

**Comment by piotrwitek** [comment]
Hey @9SMTM6, thanks for a suggestion, I agree this looks like a nice addition. Accepting PRs!
