### ISSUE TITLE
Feature request: New type `Required<T, K>` to complement `Optional<T, K>`

### ISSUE THREAD

**Issue by vhenzl** [piotrwitek/utility-types#93]
Created as per https://github.com/piotrwitek/utility-types/pull/82#issuecomment-491581958

Implementation should be straightforward:

```
type SomeRequired<T extends object, K extends keyof T = keyof T> = Omit<T, K> & Required<Pick<T, K>>;
```

Not sure about naming. Can't be `Required` as it conflicts with the built-in type. Any better idea than `SomeRequired`?

**Comment by piotrwitek** [comment]
`Required` is fine, as it's a superset and is compatible with native Required so
Local imports will not break any of the global references.
