### ISSUE TITLE
New Type: `Arguments` to return arguments of function

### ISSUE THREAD

**Issue by Harshit369** [piotrwitek/utility-types#94]
Requesting a generic `Arguments<F>` or `Args<F>` to extract out argument types of the passed function type. I have implemented it locally as:

```ts
type Args<F extends (...args: any) => any> = F extends (...args: infer A) => any
  ? A
  : never;
```

It would be nice to have it here.

**Comment by levenleven** [comment]
Typescript has builtin `Parameters` utility which does exactly this

**Comment by Harshit369** [comment]
@levenleven thanks for the info. I was using own custom declaration till now & wasn't aware of that. I am now.

**Comment by piotrwitek** [comment]
I assume it could be closed now, no?
