### ISSUE TITLE
Export alias `Falsy` for existing `Falsey`

### ISSUE THREAD

**Issue by ssalka** [piotrwitek/utility-types#96]
## Is your feature request related to a real problem or use-case?
It's a real problem to me; I prefer to spell this word as `Falsy`, not `Falsey`.

## Describe a solution including usage in code example
Add the following to `mapped-types.ts`:
```ts
/**
 * Falsy
 * @desc Type representing falsy values in TypeScript: `null | undefined | false | 0 | ''`.
 * <br>Alias for `Falsey`
 * @example
 *   type Various = 'a' | 'b' | undefined | false;
 *
 *   // Expect: "a" | "b"
 *   Exclude<Various, Falsy>;
 */
export type Falsy = Falsey;
```

## Who does this impact? Who is this for?
Spelling-sensitive users of this wonderful library such as myself 🙂

## Describe alternatives you've considered (optional)
Have done this once or twice, but for obvious reasons it is annoying to do:
```ts
import { Falsey as Falsy } from 'utility-types';
```

## Additional context (optional)
[Falsy on MDN](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)
[Is it “falsy” or “falsey”?](https://english.stackexchange.com/questions/109996/is-it-falsy-or-falsey)
[“Falsy” vs “Falsey” – I’m Making the Call](https://www.andrewzammit.com/blog/falsy-vs-falsey-im-making-the-call/)

**Comment by piotrwitek** [comment]
Hey @ssalka,
I agree with you, Falsy is far more common and also seems like a more correct form, although Falsey is acceptable.

I accept this proposal. 
For now, we would add an alias `Falsy` deprecating the use of Falsey to be removed in the next major version.
