### ISSUE TITLE
Opaque type

### ISSUE THREAD

**Issue by dimitropoulos** [piotrwitek/utility-types#98]
## Is your feature request related to a real problem or use-case?

A clear description of the problem has already been written in [this](https://codemix.com/opaque-types-in-javascript/) blog post.  A fun example of why this matters (lives could be at stake! (only kinda kidding)) can be viewed [here](https://news.ycombinator.com/item?id=15942370).

Also, this is a feature Flow has that TypeScript does not.

## Describe a solution including usage in code example

```ts
type Opaque<K, T> = T & { __TYPE__: K };
```

Perhaps the same thing could be accomplished without needing two arguments:
```ts
type Opaque<T> = T & {__TYPE__: T };
```

## Who does this impact? Who is this for?

All Users

## Describe alternatives you've considered (optional)

There are no alternatives that solve the use-case problem.  The only other thing to do is just alias, which is itself a subset of the problem.

I'd happily make a PR if you agree this would bring value.

**Comment by piotrwitek** [comment]
Hi, we already have Brand type: https://github.com/piotrwitek/utility-types#brandt-u

Also google Brand typescript for more info.

**Comment by dimitropoulos** [comment]
great. thanks.  Would you consider a PR that would simply add "Similar to Opaque types from Flow" to Brand's description?

**Comment by piotrwitek** [comment]
@dimitropoulos yes sure, sounds good!

**Comment by dimitropoulos** [comment]
https://github.com/piotrwitek/utility-types/pull/102
